sudo: required
dist: trusty

before_install:
  - sudo apt-get install linux-headers-4.4.0-51-generic linux-headers-generic
  - wget https://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb
  - wget http://download.virtualbox.org/virtualbox/5.0.24/virtualbox-5.0_5.0.24-108355~Ubuntu~trusty_amd64.deb
  - sudo dpkg -i virtualbox-5.0_5.0.24-108355~Ubuntu~trusty_amd64.deb
  - sudo /usr/lib/virtualbox/vboxdrv.sh setup
  - VBoxManage --version

script:
  - sudo ufw disable
  - VAGRANT_LOG=info vagrant up node1
  - ip addr
  - route -n
  - vagrant ssh node1 -c "sudo /vagrant/bootstrap --vip=192.168.77.201"
