- name: download networkd binary file from github release
  get_url:
    url: https://github.com/laincloud/networkd/releases/download/{{ networkd_version }}/networkd
    dest: /usr/bin/networkd
    force: yes
    mode: 777
    use_proxy: yes
  environment: "{{proxy_env}}"

- name: generate /lib/systemd/system/networkd.service
  template: src=networkd.service.j2 dest=/etc/systemd/system/networkd.service

- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: systemctl restart networkd && systemctl enable networkd
  service:
    name: networkd
    state: restarted
    enabled: yes
